### ISSUE TITLE
Problem with Sonar 4.3.1 Alrt -> Quality Gates

### ISSUE THREAD

**Issue by petterl** [TouK/sonar-file-alerts-plugin#1]
When adding this plugin to Sonar 4.3.1 you get an error like:
java.lang.ClassNotFoundException: org.sonar.api.profiles.Alert

This is because of the move of Alerts from profiles to Quality Gates in Sonar.
https://github.com/SonarSource/sonarqube/commit/1c2545e146ab0067c928363b62a57d7a206f22b3

I haven t found the exact solution for this yet.

**Comment by SpOOnman** [comment]
@petterl this project is on hold, as I'm commited to simpler alternative - sputnik. If you'd like to fix this issue with a pull request, I will merge it.
